version: "3.3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=computers

    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
    ports: 
      - 5432:5432
   

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080